version "4.1.3"

// Basic variables to customize player
#include "zscript/SideScrollerGame.zc"

// Side scrolling framework
#include "zscript/SideScrollerHandler.zc"

// Camera
#include "zscript/SideScrollerCamera.zc"

// Player Pawn (movement code goes in here)
#include "zscript/player/SideScrollerPlayer.zc"

// The states (animation) for the player
#include "zscript/player/SideScrollerPlayerStates.zc"

// HUD
#include "zscript/SideScrollerHUD.zc"
