version "2.4"

// Basic variables to customize player
#include "zscript/SideScrollerGame.zsc"

// Side scrolling framework
#include "zscript/SideScrollerHandler.zsc"

// Camera
#include "zscript/SideScrollerCamera.zsc"

// Player Pawn (movement code goes in here)
#include "zscript/player/SideScrollerPlayer.zsc"

// The states (animation) for the player
#include "zscript/player/SideScrollerPlayerStates.zsc"
